name: ghostvize
favicon: null
layout_spectrum: 0.8358
typography_spectrum: 0.34974
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fdfdfd'
    - '#8f8f8f'
    - '#f68a1e'
    - '#de2728'
  brandStrength: 0.48168699257075787
  lightness: 0.3125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
